### ISSUE TITLE
Error Launching

### ISSUE THREAD

**Issue by RXM307** [espes/Slave-in-the-Magic-Mirror#21]
Getting this error after immediately after launching 

$pypy airplay.py
Traceback (most recent call last):
  File "app_main.py", line 72, in run_toplevel
  File "airplay.py", line 30, in <module>
    import aac
  File "/home/username/Slave-in-the-Magic-Mirror/aac.py", line 33, in <module>
    Flag("frameLengthFlag"),
TypeError: 'Mapping' object is not callable

**Comment by ianquu** [comment]
have the same issue

centos 7

**Comment by AhmedX6** [comment]
same issue here

**Comment by Scvairy** [comment]
You need pypy construct module with version less then 2.8 ( pypy -m pip install 'construct<2.8' )
